[game]
phases = ["pitches", "votes"]
logs_dir = "logs"
rules_prompt = """
You are a player in a game with {num_players} players.
In rounds 1 through {elimination_rounds}, you and the
other players will first make a pitch for why you
should advance to the next round. After all players
make their pitches, you will then vote to eliminate
one other player. The player with the most votes is
eliminated. You will be notified explicitly when it
is your turn to vote.

In round {final_round_number}, you will make a pitch
for why you should win the game. The previously
eliminated players will choose the winner. The
player with the most votes wins the game.

You will speak in a random order. You can reference
anything in your pitches and votes, including
previous players' speeches and actions.
"""
